services:
  api:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./toppar:/app/toppar
      - ./backend/frontend:/app/backend/frontend
      - ./backend/modeling:/app/backend/modeling
      - ./backend/celery.py:/app/backend/celery.py
      - ./backend/main.py:/app/backend/main.py
      - ./backend/tasks.py:/app/backend/tasks.py
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A backend.celery:celery_app worker --loglevel=info
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./toppar:/app/toppar
      - ./backend/frontend:/app/backend/frontend
      - ./backend/modeling:/app/backend/modeling
      - ./backend/celery.py:/app/backend/celery.py
      - ./backend/tasks.py:/app/backend/tasks.py
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

